### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by cgsheeh** [mozilla-releng/treestatus#54]
Last week we migrated from using the RelEng Treestatus to Lando-Treestatus. We should archive this repo, and also add a link to the README that points at the new [Treestatus URL](https://lando.services.mozilla.com/treestatus/). RelEng may also need to co-ordinate with CloudOps to tear down any resources the old Treestatus was using.

**Comment by jcristau** [comment]
I'm tracking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1903226; closing this issue so it doesn't linger when the repo gets archived.  Thanks!
